version: "3"
services:
   bot:
      build: src/
      entrypoint:
      - python
      - startVoid.py
      depends_on:
      - db
      restart: always
   db:
      image: postgres:11-alpine
      volumes:
      - "db_data:/var/lib/postgresql/data"
      restart: always

volumes:
   db_data:
